### ISSUE TITLE
A small error in Key Concepts Documention.

### ISSUE THREAD

**Issue by gnahZ-eH** [odpi/egeria-docs#138]
Document Link: https://odpi.github.io/egeria-docs/introduction/key-concepts/

In the **Metadata types** part, 
Under "An example: GlossaryTerm, RelationalColumn and SemanticAssignment", the 3rd paragraph:
"... it is defined using a RelationshipDef (another subtype of EntityDef, this time specific to relationships). "

I think "another subtype of EntityDef" should change to "another subtype of TypeDef".

![image](https://user-images.githubusercontent.com/17507934/140267867-5440d2e1-b455-4f37-a250-b318d0a779f6.png)

**Comment by cmgrote** [comment]
Good catch, you're right!  Would you like to make the change and submit it via PR?

**Comment by gnahZ-eH** [comment]
> Good catch, you're right! Would you like to make the change and submit it via PR?

sure, will create a PR later
