### ISSUE TITLE
Docs Broken Link

### ISSUE THREAD

**Issue by sceo76** [odpi/egeria-docs#155]
https://egeria.odpi.org/Content-Organization.html

https://egeria.odpi.org/open-metadata-implementation/user-interfaces

**Comment by mandy-chessell** [comment]
Where are these linked called from?

**Comment by sceo76** [comment]
My apologies Mandy, the first link above is a working page that calls the 2nd (broken) link.

**Comment by mandy-chessell** [comment]
I can not get either to work :) 
The cause is that `https://egeria.odpi.org` used to redirect to the main Egeria repository and it is now redirecting to the new docs site and the content is different.

**Comment by sceo76** [comment]
You are correct... I had the first link open in a tab from yesterday. The migration must have happened in the last 24 hours as all the tabs I had open from yesterday are now broken. I've switched over to the new docs site now and all good! I'll close this ticket. Thanks!
