### ISSUE TITLE
Typo on "The Challenge" page.

### ISSUE THREAD

**Issue by sceo76** [odpi/egeria-docs#161]
Hi, I spotted a typo in the docs.

https://odpi.github.io/egeria-docs/introduction/challenge/

In the 4 bullets at end of page, 2nd bullet 'envirohment'.

If there is a single ticket for typos like this let me know and I'll add to that rather than create a new ticket as I find any.

**Comment by planetf1** [comment]
If you search and find related typos, it would be fine to add to the issue, but if not a new one is fine too. 

If you'd like to create a PR and offer a fix that would be great - otherwise let me know and i'll fix

**Comment by planetf1** [comment]
Added fix into upcoming PR.

**Comment by planetf1** [comment]
docs updated, closing
