### ISSUE TITLE
Document the 2 new properties to KafkaTopic

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-docs#171]
#5926 added 2 new properties to KafkaTopic

**Comment by davidradl** [comment]
there are 2 new properties in Type  "KafkaTopic"; they are both integers. Here are the names and descriptions:
        final String attribute1Name            = "partitions";
        final String attribute1Description     = "Number of Kafka partitions.";
        final String attribute2Name            = "replicas";
        final String attribute2Description     = "Number of Kafka replicas.";

This issue is to update the draw.io files to include the 2 new properties

**Comment by adinhtdsibm** [comment]
Do you want me to update anything in this image from this link https://egeria-project.org/concepts/extended-properties/?h=kafkatopic

**Comment by mandy-chessell** [comment]
This is already completed - https://egeria-project.org/types/2/0223-Events-and-Logs/
