### ISSUE TITLE
broken links on OMVS page

### ISSUE THREAD

**Issue by bfarasyn** [odpi/egeria-docs#177]
on the page https://odpi.github.io/egeria-docs/services/omvs/
following links do not work

- https://odpi.github.io/egeria-docs/services/omvs/glossary-author/
- https://odpi.github.io/egeria-docs/services/omvs/rex/
- https://odpi.github.io/egeria-docs/services/omvs/tex/
- https://odpi.github.io/egeria-docs/services/omvs/dino/

**Comment by planetf1** [comment]
Fixed links in upcoming PR

**Comment by planetf1** [comment]
docs updated, closing
