### ISSUE TITLE
Broken link to https://odpi.github.io/egeria-docs/services/

### ISSUE THREAD

**Issue by rrehman-hbk** [odpi/egeria-docs#206]
Please update the link
page in which url appears: https://odpi.github.io/egeria-docs/introduction/overview/#integration-services
url: https://odpi.github.io/egeria-docs/services/

**Comment by planetf1** [comment]
Agreed. We have a hierarchy of services/service types listed but maybe not an introduction to act as that link yet. keeping open.

**Comment by planetf1** [comment]
This URl seems fixed now
