### ISSUE TITLE
Link broken on the top readme

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-docs#22]
The community guid link on the top readme is broken.
https://github.com/odpi/egeria-docs/blob/main/README.md

**Comment by cmgrote** [comment]
@adinh808 any chance you want to take this one on as well? 🙏

**Comment by adinh808** [comment]
At your service :smiley:

From where should I take the content and update the Readme.md? Is it from https://github.com/odpi/egeria README file?

**Comment by cmgrote** [comment]
It's just the link in this existing README is pointing to the wrong location -- if you can just point it to the Community Guide at odpi.github.io/egeria-docs/guides/community that should do the trick

**Comment by adinh808** [comment]
What I meant was, as this was just only a Community link update, should I add more info to ReadMe file as creating a PR just to update a link will not be good. 

I have updated the Community link in README file and a [PR](https://github.com/odpi/egeria-docs/pull/23) is raised.

**Comment by cmgrote** [comment]
No problem from my side if a PR is simple 😁
