### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by dwolfson** [odpi/egeria-docs#257]
From: 
https://odpi.github.io/egeria-docs/guides/operations/kubernetes/charts/base/#accessing-egeria

Clicked on "lab-chart" and it was a broken link - link seems to be https://odpi.github.io/egeria-docs/guides/operations/kubernetes/charts/base/chart_lab.md

**Comment by planetf1** [comment]
this was later raised in #377 and fixed in #387 so closing
