### ISSUE TITLE
Outline of what content should be in what GitHub repository (ultimately)

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria-docs#260]
To capture an overall strategic outline of what repositories we should have, and what content should be in each.  Should form a "roadmap" that we gradually drive towards with separating out the core repository content + provide initial documentation for what all the repositories are, why the exist, and where to go for what.

**Comment by planetf1** [comment]
We have a list of repos in egeria-docs, and now have a template for new egeria repos.
Trying to be definitive on when to create repositories has been problematic, though we're erring towards smaller, simpler repos vs monorepos.
Therefore no particular action to be tracked by this issue -> suggest we close @cmgrote

**Comment by planetf1** [comment]
No further comments, so closing. please reopen if we need to discuss further
