### ISSUE TITLE
Broken links on community guide page

### ISSUE THREAD

**Issue by bfarasyn** [odpi/egeria-docs#261]
on page https://odpi.github.io/egeria-docs/guides/community/
the links to 
https://odpi.github.io/egeria-docs/guides/education/previous-webinars and 
https://odpi.github.io/egeria-docs/guides/education/planned-webinars  are broken

**Comment by adinhtdsibm** [comment]
@davidradl Any place where the previous-webinars are stored where I can refer to the links and update the page?
