### ISSUE TITLE
Broken links in Egeria Introduction 

### ISSUE THREAD

**Issue by fedtried** [odpi/egeria-docs#271]
Broken links:

1. Egeria docs issues -> https://egeria-project.org/education/egeria-dojo/running-egeria/egeria-introduction/
2. Egeria docs website -> https://egeria-project.org/education/egeria-dojo/running-egeria/egeria-introduction/
3. Egeria docs issues -> https://egeria-project.org/education/egeria-dojo/running-egeria/running-egeria-summary/

**Comment by planetf1** [comment]
Thanks - useful feedback. Agree that most likely it's docs issues that would be relevant for the dojo.
The odpi.github.io change was caused by a change we made to the website configuration last week - so thanks for spotting!

**Comment by planetf1** [comment]
On that second change - searching for that base URL shows we have another 15 or so places where this is now broken.
(from a github search in this repository)

Not all those links are bad -- for example https://odpi.github.io/egeria links are ok - that is specifically pointing to the egeria repo. https://odpi.github.io/egeria-charts is fine, again that is going to a specific repo. The problem arises where we had odpi.github.io/<everything else> pointing to egeria-docs. So they do need checking 1 by 1.

Would you like to create a PR for those too? :-)

**Comment by fedtried** [comment]
Yep, I can check and change those too :D
