### ISSUE TITLE
Fixing https://odpi.github.io/ links 

### ISSUE THREAD

**Issue by fedtried** [odpi/egeria-docs#286]
There's a few places where https://odpi.github.io/ is in the docs. Going through 1 by 1 to check either:
1. They're meant to be there (ie redirecting to another repository)
2. They're incorrect and lead to a 404 error

Then fixing the links which are incorrect.

**Comment by planetf1** [comment]
Thanks.. 

When you run a build of the docs `mkdocs serve` it will report which link are bad. We still have a backlog. the output may be useful to locate the affected files. The same output should be found from the build (see 'Actions' menu, and check the output)

**Comment by JonahLuckett** [comment]
@davidradl Can I get assigned to this, please

**Comment by planetf1** [comment]
closing as I think this is done
