### ISSUE TITLE
Capitalisation discussion

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-docs#30]
Overall the structure is looking excellent.  Here are some specific comments ...

* Under "Overview" -> "Our Solution"
    * "OMAG server" title should be "OMAG Server" - this is a reoccuring problem - OMAG Server Platform is consistent capitalized but "OMAG Server" is not - nor are the different types of OMAG Server.  They are often referenced in lower case eg "Metadata access point" rather than "Metadata Access Point".
    * ~~The description of the servers is not accurate...~~ --> see #31
* ~~Under "Overview/Key Concepts"~~ --> see #32
* ~~Should the road map and status (https://egeria.odpi.org/open-metadata-publication/website/roadmap/) be under "Overview" with links to releases ?~~ --> see #33 
* ~~Under "Using":~~ --> see #34 
* ~~Under "References/Services"~~ --> see #35

**Comment by mandy-chessell** [comment]
If we use lower case for "metadata repository" then it has to always mean the OMAG server type that is a metadata access point with an attached local repository.  It can not mean any metadata store - for example, the metadata store for Altas or IGC must never be referred to as a metadata repository.  I am not sure our use of the phrase is that well defined - both in the docs and the message definitions - however if we do clear that up the rest of the server type names are pretty unique.

**Comment by mandy-chessell** [comment]
Another thought is to change the name of our OMAG Server type "Metadata Repository" to "Metadata Access Store".  This would still allow us to distinguish whether the server has a local native metadata store or not - but avoids the confusion with the more generic use of the phrase "metadata repository"?  That could have lower impact and give us a more distinctive term to use.   Then the capitalization is of less importance?

**Comment by cmgrote** [comment]
Both very valid points -- it's a bit of a change, but I do think the latter idea would give us a tighter distinction in explaining what we're talking about at any given point rather than relying just on capitalisation: e.g. that a metadata access store can itself have an underlying metadata repository (in the any-vendor sense of the phrase)?

**Comment by mandy-chessell** [comment]
I am sorry, I can not parse the last sentence so just checking my interpretation.   Using the new name, a metadata access store will have a native open metadata repository (eg JanusGraph, Crux) configured.  Third party vendor products using the adapter pattern would connect using a repository proxy.  The repository proxy is not a metadata access point.  However it is a cohort member.

![image](https://user-images.githubusercontent.com/12354195/131298551-34671ad6-325e-485d-8779-6c4bcd5304c7.png)


In updating this diagram I realize I should have be talking about metadata server rather than metadata reposiotry - but I think the issue still stands

**Comment by cmgrote** [comment]
Yes, I took it a bit too far.  Ok, makes sense: does this work? A repository proxy can be supported by any underlying vendor metadata repository while a metadata access store is a type of metadata access point that is backed by an underlying data store (JanusGraph, Crux, etc) that implements a native open metadata repository.

(It looks like the updated diagram just says "metadata access point" twice now, I guess the lower box should be metadata access store?)

**Comment by mandy-chessell** [comment]
yes :)

**Comment by mandy-chessell** [comment]
The big advantage of the new name is that it is not an overloaded pre-existing term

**Comment by mandy-chessell** [comment]
We need to be able to make statements such as "each cohort should have at least one metadata access store" which is why the distinction between sert types is so important.

**Comment by cmgrote** [comment]
> The big advantage of the new name is that it is not an overloaded pre-existing term

Definitely! So should we go with this updated name and then the general style of all lowercase unless the name is prefixed or suffixed with Open Metadata (or an OMxx abbreviation), such as _Access Consumer OMAS_ and _Open Metadata Access Services_?

Or even leave those lowercase (giving us _access consumer OMAS_ and _open metadata access services_)?

(I still suggest either way that we only use _access services_ or _repository services_ if not formally written with the _Open Metadata_ prefix.)

**Comment by mandy-chessell** [comment]
I agree:
* use _Metadata Access Store_ as new name for the Metadata Server OMAG Server type
* use the general style of all lowercase unless the name is prefixed or suffixed with Open Metadata (or an OMxx abbreviation), such as Access Consumer OMAS and Open Metadata Access Services
* use _access services_ or _repository services_ if not formally written with the Open Metadata prefix

Good discussion :)

**Comment by mandy-chessell** [comment]
I have updated the website to use the new names
