### ISSUE TITLE
Add process docs on becoming a contributor/maintainer

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-docs#347]
We should clarify the process for becoming a maintainer/contributor. The existing docs do talk about the benefits for the subject, and badges etc, but need to also summarise the responsibilities and process for the approval (source: https://egeria-project.org/guides/project-operations/#community-members )

 - a) We should add documentation on the process to follow for nominations to our docs. I couldn't find anything currently about the proposal process, though I had thought in the past it referred to using the mailing lists -- which currently we don't really use. In an open community we should have a documented, transparent process. I am happy to write up something, but I think it should be either
 - mailing list
 - github issue
So that is is traceable.

b) We should also document (I can ;-) ) the steps a maintainer should take to respond to the resulting approval. One technical aspect I think is important also is to ensure the new contributor is added to the appropriate access group in github that allows them to be assigned issues & PR reviews (very useful).

For both maintainers and contributors we should establish if this refers to all of our repositories or a subset. I would say that the default is all. However for maintainers specifically I think we should have a mechanism to be a 'local maintainer' for a specific repository - for example someone only interested in a new connector, though even there initially it should be core maintainers that action merges etc.

I'll suggest that we discuss this at one of our TSC meetings.

**Comment by mandy-chessell** [comment]
For reference - this is where the description of how to become a maintainer/contributor is documented.

https://egeria-project.org/guides/project-operations/#contributors
https://egeria-project.org/guides/project-operations/#maintainers

This issue is about what happens after the request is made.

**Comment by planetf1** [comment]
See above for PR proposing updates to these docs
