### ISSUE TITLE
dead (internal) link in documentation

### ISSUE THREAD

**Issue by oh-data-sci** [odpi/egeria-docs#377]
i spotted a dead link.

on the page: [https://egeria-project.org/guides/operations/kubernetes/charts/base/](https://egeria-project.org/guides/operations/kubernetes/charts/base/)
a link labelled 'lab chart' leads to this (dead) url  https://egeria-project.org/guides/operations/kubernetes/charts/base/chart_lab.md. 

the context on the page is: 

> In the [lab chart](https://egeria-project.org/guides/operations/kubernetes/charts/base/chart_lab.md) we provided an example of using `kubectl port-forward`.

**Comment by planetf1** [comment]
@oh-data-sci did you want to do a PR for this?

**Comment by adinhtdsibm** [comment]
@planetf1 To which URL this should point to? I verified the old Egeria github page and couldn't see any reference there.

**Comment by planetf1** [comment]
The link there should be to https://egeria-project.org/guides/operations/kubernetes/charts/lab/
In site/docs/guides/operations/kubernetes/charts/base.md we would update the link


In the source this would be to a link of just 'lab' 

Currently the source has
```
In the [lab chart](chart_lab.md) we provided an example of using `kubectl port-forward`.
```
That `chart_lab.md` should be changed to `lab` I think

There's some info on the docs & testing at https://egeria-project.org/guides/documentation/guide/?h=mkdocs

**Comment by planetf1** [comment]
Now fixed as part of the above PR
