### ISSUE TITLE
egeria docs build allowed me to merge even though the build had not completed.

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-docs#380]
egeria docs build allowed me to merge even though the build had not completed. I merged and the build may fail after I have merged.

**Comment by planetf1** [comment]
The rules look ok 

Do you have any screenshots? Specific PR? 

<img width="806" alt="Screenshot 2022-03-16 at 14 45 54" src="https://user-images.githubusercontent.com/7292002/158617078-8f6c16e8-4c13-490b-a55d-97c0a0081318.png">

**Comment by planetf1** [comment]
I've just done a PR on docs to check --
<img width="1004" alt="Screenshot 2022-03-18 at 08 51 16" src="https://user-images.githubusercontent.com/7292002/158968410-8d8755cd-f1f0-4397-b6f9-7f9baafa0709.png">

I suspect you enabled the 'auto merge' option.

This does not merge before the checks complete. What it does is say you want to automatically merge if the checks pass. So any failure would be picked up

Please reopen if you still think there's an issue
