### ISSUE TITLE
Rancher Desktop installation guide url's broken

### ISSUE THREAD

**Issue by moudemans** [odpi/egeria-docs#385]
I was doing the dojo day 1 installation requirements when I noticed the URL's  trying to direct me to the rancher installation guide was:
<https://docs.rancherdesktop.io/installation>

While it should be:
<https://docs.rancherdesktop.io/getting-started/installation>

**Comment by moudemans** [comment]
I have fixed the issue on my [fork](https://github.com/moudemans/egeria-docs) by updating the three occurrences accordingly. The links now refer to the correct url, with specific url's per operating system.

I will create a PR shortly.

**Comment by planetf1** [comment]
Thanks! A PR would be great

**Comment by planetf1** [comment]
Hi. I added a note to the pr... more info there.  we need dco sign off

**Comment by planetf1** [comment]
I see this is fixed now. closing
