### ISSUE TITLE
Configuration connector docs - bad links

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-docs#422]
* Search for 'configuration document'
* Open https://egeria-project.org/concepts/configuration-document/?h=configuration#storage
* Scroll to 'sample implementations'
* Click on 'configuration-store-connectors module

This document is in the odpi/egeria repo, and the links within a dead/404 ie
 - Configuration Documents
 - OMAG Servers
 - OMAG Server Platform
 - here
 
 * Further, most of the links within each connector's readme are bad. We need to point back to content in egeria-docs
 * Also the readme for the configuration filestore connector (non encrypted) claims it is the default - but https://egeria-project.org/guides/admin/servers/#retrieving-the-configuration (correctly) points out encrypted is now the default.
 
 Note: These issues cross egeria & egeria-docs - most of the issues are in the former, but raising here for intent, and it's where the broader guidance needs to be (can be xferred if necessary)

**Comment by mandy-chessell** [comment]
I do not think this issue belongs in this repository because all of the broken links are in the egeria.git repository.

**Comment by mandy-chessell** [comment]
See https://github.com/odpi/egeria/pull/6442

**Comment by planetf1** [comment]
Thanks for fixing. closing here
