### ISSUE TITLE
Broken links on Base Egeria webpage

### ISSUE THREAD

**Issue by snk95** [odpi/egeria-docs#449]
In egeria-docs we have some issues with two URLs.
If you click on this link `https://egeria-project.org/guides/operations/kubernetes/charts/base/#prerequisites` and then goto `Kubernetes cluster` and `Helm` it gives 404 error

**Comment by planetf1** [comment]
Thanks for spotting. I'd be inclined to link them to our project pages 'Introduction to Helm' and 'Introduction to Kubernetes' ?

Would you like to submit a fix in a PR?

**Comment by snk95** [comment]
Hi Nigel,
Thanks for the email. I believe I have already linked those in my PR
https://github.com/odpi/egeria-docs/pull/445 and issue number is
https://github.com/odpi/egeria-docs/issues/449. Looking forward to your
feedback.

Best regards,
Sarvesh Kulkarni

**Comment by snk95** [comment]
The PR 445 is merged and issue is resolved.
