### ISSUE TITLE
broken link on documentation

### ISSUE THREAD

**Issue by msebbah** [odpi/egeria-docs#52]
The URL of the page that the broken link appears on:
https://odpi.github.io/egeria-docs/getting-started/dojo/ 
Menu "Hands-on Labs Preview"

The link on that page (right-click, and copy it) that is broken:
https://odpi.github.io/egeria-docs/getting-started/hands-on-labs/index.md

**Comment by planetf1** [comment]
Thanks for reporting. 

The original docs on configuring the labs are at https://egeria.odpi.org/open-metadata-resources/open-metadata-labs/ . If you still need helps in the labs please do ask here or via slack.

I don't think that content has moved across yet. If you would like to give this a go and open a PR you would be very welcome :-) If not we'll keep it open and try and address it in the coming weeks as we finish migrating and verifying links.

**Comment by adinhtdsibm** [comment]
@cmgrote Do you have any defined plan for this migration? I see that Day 1 Introduction is upload but has some changes to that of old egeria docs. So should I start working on this and you can provide inputs accordingly?
