### ISSUE TITLE
Embedded PPT does not display in Egeria Introduction page

### ISSUE THREAD

**Issue by Raunak-S** [odpi/egeria-docs#537]
The [Egeria Introduction page](https://egeria-project.org/education/egeria-dojo/running-egeria/egeria-introduction/) in the Egeria Dojo  includes an `iframe` to embed the introductory PPT for viewing in the browser. Instead the `iframe` is empty, and any navigations or refreshes to the page automatically downloads the PPT again.

From quickly looking into it, it appears that PPTs are only embeddable using `iframe`s when the `src` is hosted somewhere that supports embeds (i.e. Google Drive or OneDrive).

One alternative method is to convert the PPT to PDF format and point to it instead, since `iframe`s natively support displaying PDFs. Would love thoughts/feedback whether this would be desired functionality for the page. I'd also be happy to implement this if it sounds like a good enhancement, thanks!

**Comment by planetf1** [comment]
@Raunak-S That's a good spot. I agree with your proposal. I think we should leave the original .pptx etc checked in also, but render the pdf & link to that instead?

In general there's not much ppt* content within the docs/dojo, most is native markup with mkdocs but we do have a few presentations.

**Comment by Raunak-S** [comment]
Agreed - leaving the .pptx would still be useful for those who want the source. It is also still referenced in the download link on the same page.

No problem at all, thanks for getting back to me! I should have the change in soon.

**Comment by Raunak-S** [comment]
Opened PR #538 to resolve this issue
