### ISSUE TITLE
Change "Go to Github" button label on main Egeria docs page to "Star on Github"

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-docs#553]
Change "Go to Github" button label on main page to "Star on Github" 

I saw this example of a site [https://xtdb.com/](https://xtdb.com/) that has 2 buttons 
* "Get XTDB" which puts the user into the quick start guide 
* "Star on Github" which puts the user onto Github 

The labels seem to me to be more positive and directive compared to what we have. 

My reaction to this XTDB "Star on Github" was to immediately star their repo. I suggest we copy these 2 button labels.

**Comment by davidradl** [comment]
Any thoughts @mandy-chessell @lpalashevski @planetf1 ?

**Comment by planetf1** [comment]
The action confused me, in that the button doesn't actually 'star on github' - so it could be users go there and don't actually star?

I do think it's a good idea
