### ISSUE TITLE
Bad link to webinar in webinar history

### ISSUE THREAD

**Issue by pcoldico** [odpi/egeria-docs#562]
In the Egeria Overview page there is a list of Webinars, when I tried to link to the webinar from December 2019 - [New Approaches to Managing Access to Sensitive Data](https://egeria-project.org/education/previous-webinars/overview/december-2019) I get a 404 Page not found error.

**Comment by mandy-chessell** [comment]
Hopefully fixed now - there were many broken links on these pages
