### ISSUE TITLE
Configuring the integration daemon only covers the polling case

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-docs#584]
In
[https://egeria-project.org/guides/admin/servers/configuring-an-integration-daemon/#list-integration-services](https://egeria-project.org/guides/admin/servers/configuring-an-integration-daemon/#list-integration-services)

I notice that in the section `Configure an integration service` it only covers one of the 3 styles of the integration connector in the rest body. the text implies this is the the body to use , but this is only relevant for connectors with endpoints and not for the listener style.

**Comment by mandy-chessell** [comment]
Please feel free to update with whaever you think it needs ...
