### ISSUE TITLE
Typo in json example when documenting lineage integration connector configuration

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-docs#585]
[https://egeria-project.org/connectors/integration/open-lineage-event-receiver-integration-connector/?h=virtualconnection#configuration](https://egeria-project.org/connectors/integration/open-lineage-event-receiver-integration-connector/?h=virtualconnection#configuration)

in section ` Kafka topic connection configuration` the json payload is missing a double quote:

  ```
"embeddedConnection : 
                        {
```

should be 
  "embeddedConnection`"` : 
                        {

**Comment by mandy-chessell** [comment]
This should be fixed quickly ...
