### ISSUE TITLE
lineage-styles asset level design lineage clarification on lineage links

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-docs#600]
I am reading [https://egeria-project.org/features/lineage-management/overview/#lineage-styles](https://egeria-project.org/features/lineage-management/overview/#lineage-styles) and see :
<img width="725" alt="Screenshot 2022-11-22 at 10 05 29" src="https://user-images.githubusercontent.com/39792797/203286080-43c73fae-2612-424a-a920-5c9dfe73ac73.png">

For asset design lineage, what are the relationship types that correspond to the arrows and how do you decide what they should be? The text talking of linking; I assume these are "Dataflow", but these are only mentioned in the dojo under stitching [https://egeria-project.org/education/egeria-dojo/metadata-governance/overview/?h=dataflow#stitching](https://egeria-project.org/education/egeria-dojo/metadata-governance/overview/?h=dataflow#stitching).

**Comment by davidradl** [comment]
I see this [https://egeria-project.org/types/7/0750-Data-Passing/](https://egeria-project.org/types/7/0750-Data-Passing/) but unsure if this relates to the above picture.

**Comment by davidradl** [comment]
@mandy-chessell any thoughts?

**Comment by mandy-chessell** [comment]
The example is from a section discussing the different options for how much lineage information to capture - the later section talks about the different choices of relationship you can use.   DataFlow is a possible choice in this example or  ControlFlow or ProcessCall.  It depends on how the process instance is implemented - does it make a call to the source database or is the data fed into it.  Does the source database trigger the process?

**Comment by davidradl** [comment]
@mandy-chessell in my case, this information is an event from a Kafka queue , the event payload contains the source and target assets and the process details.

**Comment by mandy-chessell** [comment]
So the relationship to use depends on the process details - the event/kafka queue is not relevant because it is just the delivery system to get the lineage information to the connector.

**Comment by mandy-chessell** [comment]
I do not think this needs any updates to the docs - but if you disagree, please make some changes and I will review
