### ISSUE TITLE
Searching for entities

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-docs#711]
When testing the Atlas connector I tried searching by property 'qualifiedName' for value 'banana'

This failed in the connector 

The correct search syntax was '\\Qbanana\\E' as validated by our helper methods

This was a surprise since 'banana' would also be a valid regex, it's just that there are only literals to match

I was unable to find this in the documentation. I'm not sure if I missed it, but I we need to make it clearer how match expressions work generally. 

For each technology (inmem graph atlas xtdb .....) we need to document any limitations/caveats on search/match for each

It's possible we may have inconsistent behaviour - it may be the atlas connector is wrong, or inmemory - but we still need the docs as a reference point

I did try using a search string of 'FileFolder:file://secured/research/clinical-trials/drop-foot' after running the coco notebooks - nothing found, both quoted and unquoted

Here's some examples 
<img width="896" alt="Screenshot 2023-03-03 at 15 30 18" src="https://user-images.githubusercontent.com/7292002/222776547-4b9d9ba5-4cf8-4073-8bf8-ba531e521c9d.png">

<img width="1552" alt="Screenshot 2023-03-03 at 15 27 41" src="https://user-images.githubusercontent.com/7292002/222776503-45623cdc-9933-45c2-a9a3-4532aecfe5c5.png">

**Comment by planetf1** [comment]
The code in Atlas (ApacheAtlasOMRSMetadataCollection.java ~line 2426 has
```
                                    } else if (repositoryHelper.isExactMatchRegex(candidateValue)) {
```
as the condition. this checks for the quotes ie in OMRSRepositoryContentHelper.java ~l 2850
```
    private boolean isCaseSensitiveExactMatchRegex(String searchString)
    {
        return searchString == null
                || (searchString.startsWith("\\Q")
                    && searchString.endsWith("\\E")
                    && searchString.indexOf("\\E") == searchString.length() - 2);
    }
```

**Comment by planetf1** [comment]
The logic used in the atlas connector is quite different to inmemory & graph (and maybe should be updated), but even here clarity is needed on matchCriteria

Digging into the java doc there is some explanation of matchCriteria ie [here](https://odpi.github.io/egeria/org/odpi/openmetadata/repositoryservices/localrepository/repositoryconnector/LocalOMRSMetadataCollection.html#findEntitiesByProperty(java.lang.String,java.lang.String,org.odpi.openmetadata.repositoryservices.connectors.stores.metadatacollectionstore.properties.instances.InstanceProperties,org.odpi.openmetadata.repositoryservices.connectors.stores.metadatacollectionstore.properties.MatchCriteria,int,java.util.List,java.util.List,java.util.Date,java.lang.String,org.odpi.openmetadata.repositoryservices.connectors.stores.metadatacollectionstore.properties.SequencingOrder,int))
 which states
 ```
 matchProperties - Optional list of entity properties to match (where any String property's value should be defined as a Java regular expression, even if it should be an exact match).
```
This hints at java.util.regexp.pattern ie as per https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html and there are tutorials such as https://www.baeldung.com/regular-expressions-java -- but these clearly seem to concur that a string literal like 'banana' is a valid regex,

\\Q and \\E are used to start/end a quoted part of the regex, which can be useful when using special characters

like if I want to seach for text 'b**p' (literally!) then I could use 'b\*\*p' or maybe '\\Qb**p\\E' - with a long string the latter may be more convinient, but for simple workds a regexp will be a substring match

This behaviour needs clear documentation in any case, perhaps correction. However I may have misunderstood, so looking for explanation!

**Comment by mandy-chessell** [comment]
This issue seems to be about the Atlas Repository connector which is deprecated.
