### ISSUE TITLE
The webinar youtube video widgets are not displaying

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-docs#774]
See :
https://egeria-project.org/education/webinar-program/overview/?h=webina

**Comment by planetf1** [comment]
Fixed by adding a CSP for frames

This probably broke when I added commenting. This added a new directive to explicitly allow giscus in a frame. We previously had nothing listed for frames, and I had assumed nothing was allowed, but this was incorrect.

**Comment by planetf1** [comment]
Confirmed this now works properly on the published site.
