### ISSUE TITLE
Documentation - Link to Avro File Connector is invalid

### ISSUE THREAD

**Issue by wernerschulz** [odpi/egeria-docs#861]
Link https://egeria-project.org/connectors/resource/avro-file-resource-connector.md points to an invalid page.
Link is displayed on this web page: https://egeria-project.org/connectors/resource/jdbc-resource-connector/

**Comment by wernerschulz** [comment]
Other connectors on same display page are also not connected.

**Comment by mandy-chessell** [comment]
Thanks for spotting this :)

**Comment by mandy-chessell** [comment]
I think this is fixed, I can not find the link in error.
