### ISSUE TITLE
Documentation - Missing variable name in explanation 

### ISSUE THREAD

**Issue by JacobHudson** [odpi/egeria-docs#866]
https://egeria-project.org/guides/operations/kubernetes/charts/base/

Under Instillation heading:
"where is whatever you want to call your installed chart, and the -f is optional, if you have overriding values to supply."
Should be:
"where <name> is whatever you want to call your installed chart, and the -f is optional, if you have overriding values to supply."

<name> was written in the markdown file where it should have been `<name>`

**Comment by mandy-chessell** [comment]
Thank you for spotting this ....
